helloworld.com/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('comment/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'),
    path('category/<int:pk>/', views.PostCategoryList.as_view(), name='post_category_list'),  # 追加
    path('tag/<int:pk>/', views.PostTagList.as_view(), name='post_tag_list'),
]

helloworld.com/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/', include('diaries.urls')),
    path('reviews/', include('reviews.urls')),
    path('contact/', include('contact.urls')),
    path('videos/', include('videos.urls')),
    path('blog/', include('blog.urls')),
    path('', include('myprofile.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helloworld.com/videos/urls.py
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
    path('', views.VideoList.as_view(), name='video_list'),
    path('create/', views.VideoCreate.as_view(), name='video_create'),
    path('play/<int:pk>/', views.VideoDetail.as_view(), name='video_detail')
]

helloworld.com/videos/models.py
from django.db import models

# Create your models here.
from django.core.validators import FileExtensionValidator
from django.db import models


class Video(models.Model):
    title = models.CharField("動画タイトル", max_length=255)
    thumbnail = models.ImageField("動画サムネイル", blank=True)
    file = models.FileField(
        '動画ファイル',
        validators=[FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'mpeg', 'mpg', 'avi', 'wmv', 'flv', ''])]
    )

    def __str__(self):
        return self.title

helloworld.com/videos/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
from .models import Video
from django.urls import reverse_lazy


class VideoList(generic.ListView):
    model = Video


class VideoCreate(generic.ListView):
    model = Video
    fields = '__all__'
    success_url = reverse_lazy('videos:video_list')


class VideoDetail(generic.DetailView):
    model = Video

helloworld.com/videos/templates/videos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=divice-width, initial-scale=1">
    <title>動画アップロード</title>
    <style>
        * {
            margin: 0;
        }

        body {
            width: 960px;
            margin: 0 auto;
            margin-top: 50px;
        }

        .video {
            width: 160px;
            display: inline-block;
            margin-bottom: 20px;
        }

        img, video {
            width: 100%;
            height: auto;
        }
    </style>
</head>
<body>
    <p>
        <a href="{% url 'videos:video_list' %}">動画一覧</a>
        <a href="{% url 'videos:video_create' %}">アップロード</a>
    </p>
    {% block content %}{% endblock %}
</body>
</html>

helloworld.com/videos/templates/videos/video_detail.html
{% extends 'videos/base.html' %}

{% block content %}
    <h1>{{ video.title }}</h1>
    <video src="{{ video.file.url }}" contorols></video>
{% endblock%}

helloworld.com/videos/templates/videos/video_form.html
{% extends 'videos/base.html' %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
{% endblock%}

helloworld.com/videos/templates/videos/video_list.html
{% extends 'videos/base.html' %}

{% block content %}
    {% for video in video_list %}
        <a href="">
            <div class="video">
                {% if video.thumbnail %}
                    <img src="{{ video.thumbnail.url }}">
                {% endif%}
            </div>
        </a>
        <a href="{% url 'videos:video_detail' video.pk%}"></a>
    {% endfor %}
{% endblock%}