helloworld.com/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('comment/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'),
    path('category/<int:pk>/', views.PostCategoryList.as_view(), name='post_category_list'),  # 追加
    path('tag/<int:pk>/', views.PostTagList.as_view(), name='post_tag_list'),
]

helloworld.com/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/', include('diaries.urls')),
    path('reviews/', include('reviews.urls')),
    path('contact/', include('contact.urls')),
    path('videos/', include('videos.urls')),
    path('blog/', include('blog.urls')),
    path('', include('myprofile.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helloworld.com/blog/models.py
from django.db import models
from django.conf import settings


class Tag(models.Model):
    name = models.CharField('タグ名', max_length=255, unique=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField('タイトル', max_length=32)
    text = models.TextField('本文')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')
    tags = models.ManyToManyField(Tag, verbose_name='タグ', blank=True)
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, verbose_name='投稿者')
    created_at = models.DateTimeField('作成日', auto_now_add=True)
    updated_at = models.DateTimeField('更新日', auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField('本文')
    target = models.ForeignKey(Post, on_delete=models.PROTECT, verbose_name='どの記事へのコメントか')

    def __str__(self):
        return self.text[:20]

helloworld.com/blog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Comment, Category, Tag

User = get_user_model()


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'class': 'textarea'})
        }


# 増えた
class PostSearchForm(forms.Form):
    key_word = forms.CharField(
        label='キーワード', required=False,
        widget=forms.TextInput(attrs={'class': 'input'})
    )
    category = forms.ModelChoiceField(
        label='カテゴリの選択', required=False,
        queryset=Category.objects.all(),
    )
    tags = forms.ModelMultipleChoiceField(
        label='タグの選択', required=False,
        queryset=Tag.objects.all(),
    )
    user = forms.ModelChoiceField(
        label='投稿者', required=False,
        queryset=User.objects.all(),
    )

helloworld.com/blog/views.py
from django.db.models import Q
from django.shortcuts import redirect, get_object_or_404
from django.views import generic
from .forms import CommentCreateForm, PostSearchForm
from .models import Post, Comment, Category, Tag  # 追加


class PostList(generic.ListView):
    model = Post
    ordering = '-created_at'
    paginate_by = 1

    def get_queryset(self):
        queryset = super().get_queryset()
        form = PostSearchForm(self.request.GET or None)
        if form.is_valid():
            key_word = form.cleaned_data.get('key_word')
            if key_word:
                queryset = queryset.filter(Q(title__icontains=key_word) | Q(text__icontains=key_word))
            category = form.cleaned_data.get('category')
            if category:
                queryset = queryset.filter(category=category)
            tags = form.cleaned_data.get('tags')
            if tags:
                queryset = queryset.filter(tags__in=tags).distinct()
            user = form.cleaned_data.get('user')
            if user:
                queryset = queryset.filter(writer=user)
        return queryset


class PostDetail(generic.DetailView):
    model = Post


class CommentCreate(generic.CreateView):
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(Post, pk=post_pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        return redirect('blog:post_detail', pk=post_pk)


class PostCategoryList(generic.ListView):
    model = Post
    ordering = '-created_at'
    paginate_by = 10

    def get_queryset(self):
        category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return super().get_queryset().filter(category=category)


class PostTagList(generic.ListView):
    model = Post
    ordering = '-created_at'
    paginate_by = 10

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs['pk'])
        return super().get_queryset().filter(tags=tag)

helloworld.com/blog/templates/blog/base.html
{% load blog %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hogeブログ</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
<header class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <h1 class="title"><a href="{% url 'blog:post_list' %}" class="has-text-white">Hogeブログ</a></h1>
            <h2 class="subtitle">色々な記事を書いています。</h2>
        </div>
    </div>
</header>
<div class="section">
    <div class="container">
        <div class="columns">
            <main class="column is-7">
                {% block content %}{% endblock %}
            </main>
            <aside class="column is-offset-1 is-4">
                {% create_category_and_tag_list %}
                {% create_search_form request %}
            </aside>
        </div>
    </div>
</div>
</body>
</html>

helloworld.com/blog/templates/blog/category_and_tag_list.html
<p class="menu-label">カテゴリ一覧</p>
<ul class="menu-list">
    {% for category in category_list %}
        <li><a href="{% url 'blog:post_category_list' category.pk %}">{{ category }}</a></li>
    {% endfor %}
</ul>
<p class="menu-label">タグ一覧</p>
<ul class="menu-list">
    {% for tag in tag_list %}
        <li><a href="{% url 'blog:post_tag_list' tag.pk %}">{{ tag }}</a></li>
    {% endfor %}
</ul>

helloworld.com/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block content %}
    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="field">
                <label class="label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="control">
                    {{ field }}
                    {% if field.help_text %}
                        <span class="helptext">{{ field.help_text }}</span>
                    {% endif %}
                </div>
                {{ field.errors }}
            </div>
        {% endfor %}
        {% csrf_token %}
        <button class="button is-primary" type="submit">送信</button>
    </form>
{% endblock %}

helloworld.com/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
    <article class="box">
        <h1>{{ post.title }}</h1>
        <p>投稿者: {{ post.writer }}</p>
        <p>作成日: {{ post.created_at }}</p>
        <p>更新日: {{ post.updated_at }}</p>
        <p>カテゴリ: {{ post.category }}</p>
        <p>タグ: {% for tag in post.tags.all %}{{ tag }},{% endfor %}</p>
        <hr>
        <div>
            {{ post.text | linebreaks | urlize }}
        </div>
    </article>
    
    <a class="button is-primary" href="{% url 'blog:comment_create' post.pk %}">コメントする</a>

    <section class="section">
        {% for comment in post.comment_set.all %}
            <div class="box">
                {{ comment | linebreaks | urlize }}
            </div>
        {% endfor %}
    </section>

{% endblock %}

helloworld.com/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load blog %}
{% block content %}
    {% for post in post_list %}
        <article class="box">
            <h1><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h1>
            <p>投稿者: {{ post.writer }}</p>
            <p>作成日: {{ post.created_at }}</p>
            <p>更新日: {{ post.updated_at }}</p>
            <p>カテゴリ: {{ post.category }}</p>
            <p>タグ: {% for tag in post.tags.all %}{{ tag }},{% endfor %}</p>
        </article>
    {% endfor %}

    <!-- 前へ の部分 -->
    {% if page_obj.has_previous %}
        <a href="?{% url_replace request 'page' page_obj.previous_page_number %}">前へ</a>
    {% endif %}
    <!-- 数字の部分 -->
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <span>{{ num }}</span>
        {% else %}
            <a href="?{% url_replace request 'page' num %}">{{ num }}</a>
        {% endif %}
    {% endfor %}
    <!-- 次へ の部分 -->
    {% if page_obj.has_next %}
        <a href="?{% url_replace request 'page' page_obj.next_page_number %}">次へ</a>
    {% endif %}
{% endblock %}

helloworld.com/blog/templates/blog/search_form.html
<p class="menu-label">検索フォーム</p>
<form action="{% url 'blog:post_list' %}" method="GET">
    <div class="field">
        <div class="control">
            {{ form.key_word }}
        </div>
    </div>
    <div class="field">
        <div class="control">
            <div class="select">
                {{ form.category }}
            </div>
        </div>
    </div>
    <div class="field">
        <div class="control">
            <div class="select is-multiple">
                {{ form.tags }}
            </div>
        </div>
    </div>
    <div class="field">
        <div class="control">
            <div class="select">
                {{ form.user }}
            </div>
        </div>
    </div>
    <button class="button is-primary" type="submit">検索</button>
</form>