helloworld.com/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('comment/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'),
    path('category/<int:pk>/', views.PostCategoryList.as_view(), name='post_category_list'),  # 追加
    path('tag/<int:pk>/', views.PostTagList.as_view(), name='post_tag_list'),
]

helloworld.com/myprofile/urls.py
from django.urls import path
from . import views

app_name = 'myprofile'
urlpatterns = [
    path('', views.top, name='top'),
    path('resume/', views.resume, name='resume'),
]

helloworld.com/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/', include('diaries.urls')),
    path('reviews/', include('reviews.urls')),
    path('contact/', include('contact.urls')),
    path('videos/', include('videos.urls')),
    path('blog/', include('blog.urls')),
    path('', include('myprofile.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helloworld.com/myprofile/models.py
from django.db import models

# Create your models here.

helloworld.com/myprofile/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


def top(request):
    context = {'name': 'たろう'}
    return render(request, 'myprofile/top.html', context)


def resume(request):
    return render(request, 'myprofile/resume.html')

helloworld.com/myprofile/templates/myprofile/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
</head>

<body>
	<header>profile</header>

	<nav>
		<a href="{% url 'myprofile:top' %}">TOP</a>
		<a href="{% url 'myprofile:resume' %}">Resume</a>
	</nav>

	{% block content %}{% endblock %}

</body>
</html>

helloworld.com/myprofile/templates/myprofile/resume.html
{% extends 'myprofile/base.html' %}

{% block title %}Taro's profile - 職務経歴{% endblock %}

{% block content %}
    <h1>履歴・職務経歴</h1>

    <h2>職歴</h2>
    <table>
        <tr>
            <th>2015</th>
            <td>CTOとして活躍</td>
        </tr>
    </table>
{% endblock %}

helloworld.com/myprofile/templates/myprofile/top.html
{% extends 'myprofile/base.html' %}

{% block title %}Taro's profile{% endblock %}

{% block content %}
    <h1>{{ name }}についての概要</h1>
    <p>東京に住んでいる</p>

    <h2>趣味</h2>
    <ul>
        <li>映画鑑賞</li>
    </ul>
{% endblock %}